services:
  postgres:
    image: postgres:17.4-alpine3.21
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DATABASE__HOST}
      - POSTGRES_PORT=${DATABASE__PORT}
      - POSTGRES_USER=${DATABASE__USER}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
      - POSTGRES_DB=${DATABASE__DATABASE}

volumes:
  postgres_data:
