name: Format, Lint and Type Backend Check

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: |
          cd backend
          uv sync --all-extras --dev
      - name: Run Format Check
        run: |
          cd backend
          uv run ruff format .

  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: |
          cd backend
          uv sync --all-extras --dev
      - name: Run Lint Check
        run: |
          cd backend
          uv run ruff check .

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: |
          cd backend
          uv sync --all-extras --dev
      - name: Run Type Check
        run: |
          cd backend
          uv run mypy .
